// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhm1s0ASlJI7kOTYIreA88vx2LHsiepKU',
    appId: '1:345861978832:web:c613ec22f5f06e3ef97cd5',
    messagingSenderId: '345861978832',
    projectId: 'tko-loyalty-405e2',
    authDomain: 'tko-loyalty-405e2.firebaseapp.com',
    storageBucket: 'tko-loyalty-405e2.firebasestorage.app',
    measurementId: 'G-DJ0JF72GZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcVdKEleSw5naZ-K28NIea7o_oSquIieE',
    appId: '1:345861978832:android:a6ebab3495e13a58f97cd5',
    messagingSenderId: '345861978832',
    projectId: 'tko-loyalty-405e2',
    storageBucket: 'tko-loyalty-405e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2bYX7P3EA9UPb9aETb0HdzeAllJ08RY',
    appId: '1:345861978832:ios:2f4c69dabb4dcc33f97cd5',
    messagingSenderId: '345861978832',
    projectId: 'tko-loyalty-405e2',
    storageBucket: 'tko-loyalty-405e2.firebasestorage.app',
    iosBundleId: 'com.example.tkotoylogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu2bYX7P3EA9UPb9aETb0HdzeAllJ08RY',
    appId: '1:345861978832:ios:2f4c69dabb4dcc33f97cd5',
    messagingSenderId: '345861978832',
    projectId: 'tko-loyalty-405e2',
    storageBucket: 'tko-loyalty-405e2.firebasestorage.app',
    iosBundleId: 'com.example.tkotoylogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhm1s0ASlJI7kOTYIreA88vx2LHsiepKU',
    appId: '1:345861978832:web:affc257180013ac7f97cd5',
    messagingSenderId: '345861978832',
    projectId: 'tko-loyalty-405e2',
    authDomain: 'tko-loyalty-405e2.firebaseapp.com',
    storageBucket: 'tko-loyalty-405e2.firebasestorage.app',
    measurementId: 'G-2X81XGPV8R',
  );
}
