// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'firebase_options.dart';        // generated by flutterfire configure
import 'home_page.dart';               // your main app after login
import 'login_page.dart';              // simple email/google login
import 'login_signup_page.dart';       // tabbed Sign in / Sign up (with first/last name)

// ---- Brand colors (keep consistent across app) ----
const tkoOrange = Color(0xFFFF6A00);
const tkoCream  = Color(0xFFF7F2EC);

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const TkoApp());
}

class TkoApp extends StatelessWidget {
  const TkoApp({super.key});

  // Toggle which login UI you want to use
  static const bool useTabbedLogin = true;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TKO Loyalty',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: tkoOrange,
        scaffoldBackgroundColor: tkoCream,
        appBarTheme: const AppBarTheme(
          centerTitle: true,
          backgroundColor: Colors.transparent,
          elevation: 0,
          foregroundColor: Colors.black,
        ),
      ),
      home: const AuthGate(),
    );
  }
}

class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snap) {
        // Show a lightweight splash while Firebase checks current user
        if (snap.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        // If logged in -> Home, else -> choose login screen
        if (snap.data != null) {
          return const HomePage();
        } else {
          return TkoApp.useTabbedLogin
              ? const LoginSignupPage()  // includes first/last name on sign-up
              : const LoginPage();       // simple continue-with-email-or-google
        }
      },
    );
  }
}
